version: "3.9"

services:
  app:
    image: go-redis-sample
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    environment:
      TODO_REDIS_HOST: redis-sample
      TODO_REDIS_PORT: 6379
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - redis-sample
  
  redis-sample:
    image: "redis:latest"
    container_name: redis-sample
    ports:
      - "6379:6379"
    volumes:
      - redis-sample-data:/data

volumes:
  redis-sample-data: